<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign in</name>
   <tag></tag>
   <elementGuidId>ab18285d-3fcc-42ba-8b7d-4f2f600c3dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-signin-tooltip > a.nav-action-signin-button > span.nav-action-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-signin-tooltip']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f91c73c6-e3e0-45ff-999c-c0588e4ec1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-action-inner</value>
      <webElementGuid>13a4c1e2-7af3-474a-b507-493e1bd7c610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>35adc660-77ea-4442-b9cb-23d9b6293885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-signin-tooltip&quot;)/a[@class=&quot;nav-action-signin-button&quot;]/span[@class=&quot;nav-action-inner&quot;]</value>
      <webElementGuid>1439e10b-0e7c-4377-b7c4-069ea272e549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-signin-tooltip']/a/span</value>
      <webElementGuid>7e28f009-dd46-4a78-84f2-25c73bee0293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/a/span</value>
      <webElementGuid>6a83bb23-6566-42d7-b8a7-26ddf1bdcd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>e085e019-8fe1-45be-8311-29f6349f173c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
